### PR TITLE
Fix reach ring

### LINKED ISSUE #20484: Re-equiping Ring of Far Reach increases Reach Length permanently, stacking with every time
### Your GTNH Discord Username

_No response_

### Your Pack Version

2.8.0 Beta-1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Ring of Far Reach would set Reach Range to some higher value when you have it equipped.

### The Reality

If you remove and equip the Ring many times you can stack Reach Length to over a hundred blocks. Re-entering the world sets Reach to the expected Reach amount.
More specifically, it seems that having a Ring equipped gives some Reach, which stays as long as you have it equipped, and each action of equipping it gives some more Reach, untill re-entering the world.
I think that because entering the world with the Ring already equipped and equipping and de-equipping the Ring a single time - not having it equipped at the end - has the exact same Reach above normal. If you enter the world without equipped Ring and put it on, you'll have more reach that either of the 2 previous cases. If you keep re-equipping it, the Reach will increase even more.

### Your Proposal

Fix to expected behaviour

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by DarkShadow44**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20484

Built on top of https://github.com/GTNewHorizons/Botania/pull/67, hopefully this time fixed for good..

To summarize, the ring has a few issue:
Primarily, it didn't get applied after a relog, that's why it got handled in `onWorkTick` as well.
Problem is, after unequip we might get another tick, which might reapply the effect erroneously.
The current code deal with that by expecting that tick and handling it.
Additional issue is the shared state of client/server in SP (`toRemoveItems`)
Since expecting (and needing) the ticks is a pain to deal with, I replaced it with a short delay - those weird ticks after unequip are now ignored and don't execute any logic. Should make it easier to understand and hopefully fix this issue.

@Shadow1590 Since you are the original author, mind taking a look as well?

### CODE REVIEW

**Comment by Shadow1590** [comment]
The code looks fine by me. (But im not gonna review cause im not part of the org)
Although i have to say that all the worntick stuff is there because baubles doesnt have anything that fires only on login/load into world. So if anyone can and wants to do that it would remove the need for at least this bauble to be tickable.

**Comment by Dream-Master** [comment]
@Shadow1590 i can add you to the org if you can review PRs .

**Comment by Shadow1590** [comment]
> > The code looks fine by me. (But im not gonna review cause im not part of the org) Although i have to say that all the worntick stuff is there because baubles doesnt have anything that fires only on login/load into world. So if anyone can and wants to do that it would remove the need for at least this bauble to be tickable.
> 
> There is a `PlayerJoinEvent` provided by Forge. Why not scan the Baubles inventory whenever a player logs on and activate their Ring?

Sure, but i think that should be part of baubles and not here.
I didnt originally do it because i havent found another bauble that would benefit from it. If there would be more baubles I can make something.

**Comment by DarkShadow44** [comment]
> The code looks fine by me. (But im not gonna review cause im not part of the org) Although i have to say that all the worntick stuff is there because baubles doesnt have anything that fires only on login/load into world. So if anyone can and wants to do that it would remove the need for at least this bauble to be tickable.

Yeah I understand.

> I don't think this is the way you should fix it. You're essentially fixing the issue, but not the root cause. The underlying issue is that the function setReach() gets called twice on the client when equipping the ring (and only once when unequipping).

Not really. The first underlying issue is that onEquipped isn't called after logging in
The second issue, with the current approach, is that there are onWornTicks after it's unequipped, which confuses the code.


> There is a `PlayerJoinEvent` provided by Forge. Why not scan the Baubles inventory whenever a player logs on and activate their Ring?


Could be an option, I just worked on what we have already. Should we move this to baubles? Should probably not call onEquipped directly though, since other baubles might not expect it twice.

**Comment by Nikolay-Sitnikov** [comment]
> > The code looks fine by me. (But im not gonna review cause im not part of the org) Although i have to say that all the worntick stuff is there because baubles doesnt have anything that fires only on login/load into world. So if anyone can and wants to do that it would remove the need for at least this bauble to be tickable.
> 
> Yeah I understand.
> 
> > I don't think this is the way you should fix it. You're essentially fixing the issue, but not the root cause. The underlying issue is that the function setReach() gets called twice on the client when equipping the ring (and only once when unequipping).
> 
> Not really. The first underlying issue is that onEquipped isn't called after logging in The second issue, with the current approach, is that there are onWornTicks after it's unequipped, which confuses the code.
> 
> > There is a `PlayerJoinEvent` provided by Forge. Why not scan the Baubles inventory whenever a player logs on and activate their Ring?
> 
> Could be an option, I just worked on what we have already. Should we move this to baubles? Should probably not call onEquipped directly though, since other baubles might not expect it twice.

Honestly, I'd leave it as-is and just implement the event into Botania's code directly. This removes the worn tick after taking it off problem, and it doesn't require Baubles API to get modified.

If you really want, you could probably add an interface & an event to Baubles, but that would require another PR while most mods wouldn't need it.

**Comment by DarkShadow44** [comment]
I could use `PlayerLoggedInEvent` for server side, but that doesn't fire client side. What event do I use to detected that a client has joined a server/SP?

**Comment by Shadow1590** [comment]
I found a problem.
when you log out of singleplayer with a reach ring and then log in to a server where you dont have one equipped it still applies the reach client side (seems like the bauble inventory is not synced yet)
Im also seing two onEquipped calls on client (but that maybe is a baubles thing, because i cant find any call for that in botania)
Im now thinking it should just get synced from server to client via a packet or something

**Comment by DarkShadow44** [comment]
> I found a problem. when you log out of singleplayer with a reach ring and then log in to a server where you dont have one equipped it still applies the reach client side (seems like the bauble inventory is not synced yet) Im also seing two onEquipped calls on client (but that maybe is a baubles thing, because i cant find any call for that in botania) Im now thinking it should just get synced from server to client via a packet or something

Thanks for the report, since syncing should be done by baubles I decided to finally put in a PR to baubles itself: https://github.com/GTNewHorizons/Baubles-Expanded/pull/14

Of course, this doesn't compile now since it references old baubles, but it should be enough for review and testing, I hope.
I think this is the cleanest way now.

**Comment by DarkShadow44** [comment]
This is ready now!

File: src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java [hunk 1]
```diff
@@ -151,17 +142,16 @@ public void onEquipped(ItemStack stack, EntityLivingBase player) {
...
+	@Override
+	public void onUnequipped(ItemStack stack, EntityLivingBase player) {
 		// NO-OP
 	}
 
-	@Override
-	public void onUnequipped(ItemStack stack, EntityLivingBase player) {
-		toRemoveItems.add(getBaubleUUID(stack));
+	public void onEquippedOrLoadedIntoWorld(ItemStack stack, EntityLivingBase player) {
+		// NO-OP
```
Comment (combusterf) [inline src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java:154]: This method was added, but doesn't appear to have any usages. Please remove if it's no longer necessary.

Comment (DarkShadow44) [reply src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java:154]: `onEquippedOrLoadedIntoWorld` is still used, it's just a no-op in ItemBauble, it's called and overriden.

**Review by combusterf — APPROVED** [review]

**Comment by Twilight2** [comment]
> This is ready now!

Seems works bad with Lotr mod

**Comment by DarkShadow44** [comment]
> Seems works bad with Lotr mod

Because of the issue this Pr fixes? https://github.com/GTNewHorizons/Baubles-Expanded/pull/21
Or something else? You're not giving me any info here...

**Comment by Twilight2** [comment]
> > Seems works bad with Lotr mod
> 
> Because of the issue this Pr fixes? [GTNewHorizons/Baubles-Expanded#21](https://github.com/GTNewHorizons/Baubles-Expanded/pull/21) Or something else? You're not giving me any info here...

I'll try soon, too much mod in my pack(400+)

**Comment by combusterf** [comment]
> Seems works bad with Lotr mod

A good error report contains at least the following:
- What did you do
- What did you expect to happen
- What did actually happen
- Exact version of the Botania mod

**Comment by Twilight2** [comment]
> > Seems works bad with Lotr mod
> 
> Because of the issue this Pr fixes? [GTNewHorizons/Baubles-Expanded#21](https://github.com/GTNewHorizons/Baubles-Expanded/pull/21) Or something else? You're not giving me any info here...

game version:
1.7.10 forge 1614

mods:
BaublesExpanded-2.1.19-GTNH
+unimixins-all-1.7.10-0.1.23
LOTRMod v36.15
hodgepodge-2.7.5
Botania-1.13.14-GTNH(or 1.9.11-gtnh/r1.8-249-not gtnh)
gtnhlib-0.8.34
lwjgl3ify-3.0.13

issue:
The reach ring does not work in the first time, whether for breaking blocks or hitting creatures.
After rejoin the test world now I can breaking blocks far away but can't hitting a creature at the same distance,and the effect won't disappear after remove the reach ring even rejoin the world again.
Everything works fine after delete Lotr mod.
